motivation_messages = [
    "🥳 Disiplin kazanmanın anahtarıdır!",
    "⭐ Şans, hazırlıkla fırsatın buluşmasıdır!",
    "🎈 Her kayıp, daha güçlü bir sinyalin habercisidir!",
    "💎 Soğukkanlı kal, stratejine sadık kal!",
    "🎯 Odaklan, doğru anı bekle!",
    "🎊 Sabırlı ol, sonuç gelecek!",
    "🔥 Devam et, başarı seninle!",
    "🏆 Büyük kazançlar sabır ister!",
    "🪅 Şansın bol olsun!",
    "💪 Tutarlılık kazandırır!",
    "🍾 Bugün kazanma günün!",
    "💡 Her sinyal yeni bir fırsattır!",
    "🎲 Stratejine güven, kazanacaksın!",
    "🎉 Pes etme, kazanmaya yakınsın!",
    "⚡ Disiplin + Sabır = Başarı!",
    "🥂 Büyük resme bak, küçük dalgalanmalar önemli değil!",
    "📊 Veri yalan söylemez, stratejine güven!",
    "⏳ Sabır en büyük silahındır!",
    "🧠 Duygularını kontrol et, stratejini uygula!",
    "💎 Her kayıp aslında bir derstir!",
    "🎯 Hedefine odaklan, gerisi teferruat!",
    "🔄 Her döngüde daha da güçleneceksin!",
    "✨ Başarı, sıradan şeyleri sıradan insanlardan daha uzun süre yapmaktır!",
    "🚀 Büyük kazançlar için küçük adımlarla yürü!",
    "🎁 Şans, hazır olanı sever!",
    "💪 Kaybetmek asla pes etmek değildir!",
    "🎈 Sakin ol, doğru anı bekle!",
    "🔥 Bu seride patlama yapma zamanı!",
    "⚡ Disiplinli ol, kazançlar gelecek!",
    "🎊 Her şey gönlünce olsun, rahat ol!",
    # ========= EĞLENCE + KLASİK KARIŞIM EKLER =========
    "💖 Kazanmaya odaklan, gerisi teferruat!",
    "😍 Bu sinyal tam sana göre, hadi!",
    "👏 Harika bir fırsat, kaçırma!",
    "🎉 Kutlama zamanı yakın, inan!",
    "🕺 Dans et, çünkü kazanacaksın!",
    "🌟 Yıldızlar seninle, korkma!",
    "💥 Patlama yapma vakti geldi!",
    "🤩 Gözlerini yumma, büyük anı gör!",
    "🎯 Hedef 12'den vur, emin ol!",
    "🚀 Roket gibi fırla, durma!",
    "💎 Elmas gibi değerli bu sinyal, değerlendir!",
    "🍾 Şampanyayı patlatmaya hazır mısın?",
    "💃 Sevinçle zıpla, kazanç kapıda!",
    "⭐ Sakin ol, ama kazanacağını bil!",
    "🏆 Bu sinyal senin için, al ve koş!"
]
